### PR TITLE
Add MIT license

### PR DESCRIPTION
**Pull request by todoubled**
I'd be more comfortable using this if it had a license. Are there any objections to MIT, chosen from http://choosealicense.com/?

Thanks for maintaining this lib!

### CODE REVIEW

**Comment by sieira** [comment]
Unfortunately, I can't do this without the consent of the original maintainers, I'll give it a look tomorrow. I'd like to license it as well, avoids a lot of trouble

**Comment by briankircho** [comment]
I am the original maintainer, this is fine with me I usually go with MIT guess I just forgot to add it

**Comment by todoubled** [comment]
Great, thanks guys. I updated this to use your full name @briankircho, so it should be good to go.

**Comment by sieira** [comment]
Ok, merged, thanks :)

**Comment by todoubled** [comment]
Thanks @sieira! Would it be possible to get a new version released to include the license too?

**Comment by sieira** [comment]
It's done, I hope there are no regressions (proxies may be a problem for now)

**Comment by todoubled** [comment]
@sieira Thanks! Can you please elaborate on the potential proxies problem? I'm not quite sure what that refers to.

**Comment by sieira** [comment]
See my last comment here https://github.com/briankircho/mongoose-schema-extend/issues/39

**Pull request merged**
